Don't fail on no args

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,6 +76,11 @@ jobs:
       - run: cargo nextest run --no-tests=pass -p qt -p quilkin -p quilkin-xds quilkin
       - name: Validate Quilkin's clap arguments
         run: cargo run -p quilkin
+          if [ $? -ne 255 ]; then
+            echo "::error ::clap arguments seem to have an error"
+            exit 1
+          fi
+          exit 0
 
   build:
     name: Build
