Add check that clap arguments are valid

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,6 +74,14 @@ jobs:
       - name: Build
         run: cargo build -p qt -p quilkin -p quilkin-xds --tests
       - run: cargo nextest run --no-tests=pass -p qt -p quilkin -p quilkin-xds quilkin
+      - name: Validate that quilkin arguments are valid
+        run: |
+          cargo run -p quilkin
+          if [ $? -ne 255 ]; then
+            echo "::error ::clap arguments seem to have an error"
+            exit 1
+          fi
+          exit 0
 
   build:
     name: Build
